### ISSUE TITLE
Colab error

### ISSUE THREAD

**Issue by eyetest42** [arenasys/qDiffusion#88]
Appears when generating links

> Traceback (most recent call last):
>   File "/content/sd-inference-server/remote.py", line 8, in <module>
>     import storage
>   File "/content/sd-inference-server/storage.py", line 8, in <module>
>     import models
>   File "/content/sd-inference-server/models.py", line 5, in <module>
>     from lora import LycorisNetwork
>   File "/content/sd-inference-server/lora.py", line 22, in <module>
>     import diffusers.models.lora
>   File "/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py", line 5, in <module>
>     from .utils import (
>   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/__init__.py", line 38, in <module>
>     from .dynamic_modules_utils import get_class_from_dynamic_module
>   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
>     from huggingface_hub import cached_download, hf_hub_download, model_info
> ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/__init__.py)

**Comment by talon19912** [comment]
i have that error as well

**Comment by InterspeciesFace** [comment]
Thirding this.

**Comment by arenasys** [comment]
probably fixed by bb6a19980a7eb8ce2ecd622949baccf786fccdcf

**Comment by talon19912** [comment]
nope still not working
![Screenshot 2024-11-14 233456](https://github.com/user-attachments/assets/9ddf8db1-db41-4b60-bac6-95dbb3990717)

**Comment by arenasys** [comment]
its fixed. follow the normal instructions here: https://github.com/arenasys/qDiffusion?tab=readme-ov-file#remote. remaking the instance is important if you have an existing one (`Runtime->Disconnect and delete runtime`)
